/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
Traceback (most recent call last):
  File "read_flux_files.py", line 313, in <module>
    read_flux_files(sys.argv[1], sys.argv[2], 3, 4)
  File "read_flux_files.py", line 185, in read_flux_files
    out['sfc_down_flux_all_lw(Wm-2)'].append(np.float(f.variables['all_lw_DOWNWARD FLUX_integrated'][SFC]))
KeyError: 'all_lw_DOWNWARD FLUX_integrated'
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
read_flux_files.py:126: RuntimeWarning: invalid value encountered in greater
  cwp = np.sum(f.variables['CWP'][:])
read_flux_files.py:128: RuntimeWarning: invalid value encountered in greater
  wpi = np.mean(f.variables['WPi'][:])
read_flux_files.py:131: RuntimeWarning: invalid value encountered in greater
  rice = np.mean(f.variables['ri'][:])
read_flux_files.py:136: RuntimeWarning: invalid value encountered in greater
  out['lwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(1-f.variables['WPi'][:])))
read_flux_files.py:137: RuntimeWarning: invalid value encountered in greater
  out['iwp(gm-2)'].append(np.sum(f.variables['CWP'][:]*(f.variables['WPi'][:])))
Traceback (most recent call last):
  File "average.py", line 123, in <module>
    filter_invalid=True)
  File "average.py", line 64, in average
    results = pd.read_csv(fname_in, parse_dates=['time'])
  File "/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/pandas-0.20.3-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/pandas-0.20.3-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/pandas-0.20.3-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/pandas-0.20.3-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/eb/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages/pandas-0.20.3-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'/mnt/beegfs/user/phi.richter/DATA_PHD/RRTMG/OUTPUT/CSV/OUTPUT_CSV/RRTMG_Cloudnet_cloud_plus_10.csv' does not exist
